# Generated by Django 3.2.14 on 2022-09-05 23:51

from django.db import migrations, models
import icgc_app.lsgfunctools.file_validator
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('icgc_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='game/', validators=[icgc_app.lsgfunctools.file_validator.file_validator_image])),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
