# Generated by Django 3.2.14 on 2022-09-06 00:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('icgc_app', '0002_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('pin', models.CharField(max_length=50, unique=True)),
                ('sn', models.CharField(max_length=50, unique=True)),
                ('amount', models.IntegerField()),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_amount_game', to='icgc_app.game')),
            ],
        ),
    ]
