# Generated by Django 3.2.14 on 2022-09-06 01:19

from django.db import migrations, models
import icgc_app.lsgfunctools.file_validator


class Migration(migrations.Migration):

    dependencies = [
        ('icgc_app', '0003_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='image',
        ),
        migrations.AddField(
            model_name='game',
            name='img_thumbnail',
            field=models.ImageField(blank=True, upload_to='game/thumbnail/', validators=[icgc_app.lsgfunctools.file_validator.file_validator_image]),
        ),
        migrations.AddField(
            model_name='game',
            name='img_wallpaper',
            field=models.ImageField(blank=True, upload_to='game/wallpaper/', validators=[icgc_app.lsgfunctools.file_validator.file_validator_image]),
        ),
    ]
