# Generated by Django 3.2.14 on 2022-09-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icgc_app', '0004_auto_20220906_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
