# Generated by Django 3.2.14 on 2022-09-07 05:56

from django.db import migrations, models
import icgc_app.lsgfunctools.file_validator


class Migration(migrations.Migration):

    dependencies = [
        ('icgc_app', '0006_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='img_thumbnail',
            field=models.ImageField(blank=True, upload_to='game/payment_method/', validators=[icgc_app.lsgfunctools.file_validator.file_validator_image]),
        ),
    ]
