# Generated by Django 3.2.14 on 2022-09-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icgc_app', '0007_paymentmethod_img_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='amount',
            name='points_to_earn',
            field=models.IntegerField(default=0),
        ),
    ]
