# Generated by Django 3.2.14 on 2022-09-10 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('icgc_app', '0008_amount_points_to_earn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('reference_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_transactions_amount', to='icgc_app.amount')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_transactions_game', to='icgc_app.game')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_transactions_payment_method', to='icgc_app.paymentmethod')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_transactions_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
