# Generated by Django 3.2.14 on 2022-09-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icgc_app', '0011_alter_transaction_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='charge_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
