# Generated by Django 3.2.14 on 2022-09-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icgc_app', '0012_transaction_charge_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
