# Generated by Django 3.2.14 on 2022-11-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icgc_app', '0014_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
